# Generated by Django 4.1.4 on 2022-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='item_imgs/')),
                ('inStock', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='itemNo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
