# Generated by Django 4.1.4 on 2022-12-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_category_itemno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='itemNo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
