# Generated by Django 4.1.4 on 2022-12-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothAttribute',
            new_name='ItemAttribute',
        ),
        migrations.RenameModel(
            old_name='ClothSize',
            new_name='Size',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '3. Banners'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': '2. Items'},
        ),
        migrations.AlterModelOptions(
            name='itemattribute',
            options={'verbose_name_plural': '5. ItemAttributes'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '4. Sizes'},
        ),
    ]
