# Generated by Django 4.1.4 on 2022-12-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_orderitems_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='totalAmount',
        ),
    ]
