# Generated by Django 4.1.4 on 2022-12-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_totalprice_order_totalamount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemattribute',
            options={'verbose_name_plural': 'Item Attributes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'Sizes'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
