# Generated by Django 4.1.4 on 2022-12-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phoneno',
            field=models.CharField(max_length=15),
        ),
    ]
